namespace Grace.Shared.Resources

module Text =

    /// This is intended to be the definitive list of locali[sz]ations that Grace supports.
    ///
    /// I'm starting with en-US, because that's all I know, but trying to do it right from the start.
    type Language =
        | ``EN-US``

    type StringResourceName =
        | BranchAlreadyExists
        | BranchDoesNotExist
        | BranchIdIsRequired
        | BranchIdsAreRequired
        | BranchIsNotBasedOnLatestPromotion
        | BranchNameAlreadyExists
        | BranchNameIsRequired
        | CheckpointIsDisabled
        | CommitIsDisabled
        | CreatingNewDirectoryVersions
        | CreatingSaveReference
        | DeleteReasonIsRequired
        | DescriptionIsRequired
        | DirectoryAlreadyExists
        | DirectoryDoesNotExist
        | DuplicateCorrelationId
        | EitherBranchIdOrBranchNameIsRequired
        | EitherOrganizationIdOrOrganizationNameIsRequired
        | EitherOwnerIdOrOwnerNameIsRequired
        | EitherRepositoryIdOrRepositoryNameIsRequired
        | FailedCommunicatingWithObjectStorage
        | FailedCreatingInitialBranch
        | FailedRebasingInitialBranch
        | FailedCreatingInitialPromotion
        | FailedToGetUploadUrls
        | FailedToRetrieveBranch
        | FailedUploadingFilesToObjectStorage
        | FailedWhileApplyingEvent
        | FailedWhileSavingEvent
        | FilesMustNotBeEmpty
        | GettingLatestVersion
        | GettingCurrentBranch
        | GraceConfigFileNotFound
        | IndexFileNotFound
        | InitialPromotionMessage
        | InterprocessFileDeleted
        | InvalidBranchId
        | InvalidBranchName
        | InvalidCheckpointDaysValue
        | InvalidDirectoryPath
        | InvalidDirectoryId
        | InvalidMaxCountValue
        | InvalidObjectStorageProvider
        | InvalidOrganizationId
        | InvalidOrganizationName
        | InvalidOrganizationType
        | InvalidOwnerId
        | InvalidOwnerName
        | InvalidOwnerType
        | InvalidReferenceType
        | InvalidRepositoryId
        | InvalidRepositoryName
        | InvalidRepositoryStatus
        | InvalidSaveDaysValue
        | InvalidSearchVisibility
        | InvalidServerApiVersion
        | InvalidSha256Hash
        | InvalidSize
        | InvalidVisibilityValue
        | PromotionIsDisabled
        | PromotionNotAvailableBecauseThereAreNoPromotableReferences
        | MessageIsRequired
        | NotImplemented
        | ObjectCacheFileNotFound
        | ObjectStorageException
        | OrganizationIdAlreadyExists
        | OrganizationNameAlreadyExists
        | OrganizationContainsRepositories
        | OrganizationDoesNotExist
        | OrganizationIdDoesNotExist
        | OrganizationIdIsRequired
        | OrganizationIsDeleted
        | OrganizationIsNotDeleted
        | OrganizationNameIsRequired
        | OrganizationTypeIsRequired
        | OwnerContainsOrganizations
        | OwnerDoesNotExist
        | OwnerIdDoesNotExist
        | OwnerIdAlreadyExists
        | OwnerIdIsRequired
        | OwnerIsDeleted
        | OwnerIsNotDeleted
        | OwnerNameAlreadyExists
        | OwnerNameIsRequired
        | OwnerTypeIsRequired
        | ParentBranchDoesNotExist
        | ReadingGraceStatus
        | ReferenceIdDoesNotExist
        | ReferenceIdsAreRequired
        | ReferenceTypeMustBeProvided
        | RelativePathMustNotBeEmpty
        | RepositoryContainsBranches
        | RepositoryDoesNotExist
        | RepositoryIdAlreadyExists
        | RepositoryIdDoesNotExist
        | RepositoryIdIsRequired
        | RepositoryIsAlreadyInitialized
        | RepositoryIsDeleted
        | RepositoryIsNotDeleted
        | RepositoryIsNotEmpty
        | RepositoryNameIsRequired
        | SaveIsDisabled
        | SavingDirectoryVersions
        | ScanningWorkingDirectory
        | SearchVisibilityIsRequired
        | ServerRequestsMustIncludeXCorrelationIdHeader
        | Sha256HashDoesNotExist
        | Sha256HashIsRequired
        | StringIsTooLong
        | TagIsDisabled
        | UpdatingWorkingDirectory
        | UploadingFiles
        | ValueMustBePositive
