# Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (6aba16a1a382dad6a6863382215eb4dfd2a4cf958497259e54f38ee9a3f8af16). Do not edit by hand.

API_CONTRACT_VERSION = "2023-10-01"
OPENAPI_VERSION = "3.1.2"
OPENAPI_PROJECTION = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml"
OPENAPI_PROJECTION_SHA256 = "6aba16a1a382dad6a6863382215eb4dfd2a4cf958497259e54f38ee9a3f8af16"
GENERATOR = "grace-sdk-harness"
GENERATOR_VERSION = "0.1.0"