# Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (5e1f6ee5eafe2ba086028035bd1989c2dc4d6b058935cf026c38c678818dd9d2). Do not edit by hand.

API_CONTRACT_VERSION = "2023-10-01"
OPENAPI_VERSION = "3.1.2"
OPENAPI_PROJECTION = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml"
OPENAPI_PROJECTION_SHA256 = "5e1f6ee5eafe2ba086028035bd1989c2dc4d6b058935cf026c38c678818dd9d2"
GENERATOR = "grace-sdk-harness"
GENERATOR_VERSION = "0.1.0"