# Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (f7827983847ab76b04d6787f70e7c8483542cc7ff2ceecda1ff6cbd014eeeb29). Do not edit by hand.

API_CONTRACT_VERSION = "2023-10-01"
OPENAPI_VERSION = "3.1.2"
OPENAPI_PROJECTION = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml"
OPENAPI_PROJECTION_SHA256 = "f7827983847ab76b04d6787f70e7c8483542cc7ff2ceecda1ff6cbd014eeeb29"
GENERATOR = "grace-sdk-harness"
GENERATOR_VERSION = "0.1.0"