[CmdletBinding()]
param(
    [ValidateSet('Generate', 'Check')]
    [string] $Mode = 'Generate'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$HarnessName = 'grace-sdk-harness'
$HarnessVersion = '0.1.0'
$HarnessSchemaVersion = 1

function Get-RepoRoot {
    $root = git rev-parse --show-toplevel
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($root)) {
        throw 'Unable to resolve repository root with git rev-parse.'
    }

    return $root.Trim()
}

function Get-FileSha256 {
    param([string] $Path)
    return (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function Write-Utf8NoBomLfFile {
    param(
        [string] $Path,
        [string] $Text
    )

    $directory = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($directory)) {
        New-Item -ItemType Directory -Force -Path $directory | Out-Null
    }

    $normalizedText = $Text -replace "`r`n", "`n"
    $encoding = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $normalizedText, $encoding)
}

function Get-CommandVersion {
    param(
        [string] $Command,
        [string[]] $Arguments
    )

    $resolved = Get-Command $Command -ErrorAction SilentlyContinue
    if ($null -eq $resolved) {
        return [ordered]@{
            command = $Command
            available = $false
            version = $null
        }
    }

    $versionOutput = & $Command @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    $version = ($versionOutput | Select-Object -First 1)
    if ($null -ne $version) {
        $version = $version.ToString().Trim()
    }

    return [ordered]@{
        command = $Command
        available = $true
        version = $version
        exitCode = $exitCode
    }
}

function Write-ToolVersionDiagnostics {
    param([object[]] $ToolVersions)

    Write-Host 'Observed SDK harness tool versions (diagnostic only; not part of freshness):'
    foreach ($tool in $ToolVersions) {
        if ($tool.available) {
            Write-Host "  $($tool.command): $($tool.version)"
        }
        else {
            Write-Host "  $($tool.command): unavailable"
        }
    }
}

function Get-OpenApiMetadata {
    param([string] $ProjectionPath)

    $text = Get-Content -LiteralPath $ProjectionPath -Raw
    $openApiVersion = [regex]::Match($text, '(?m)^openapi:\s*[''"]?([^''"\r\n]+)[''"]?\s*$').Groups[1].Value.Trim()
    $apiContractVersion = [regex]::Match($text, '(?m)^\s*version:\s*[''"]?([^''"\r\n]+)[''"]?\s*$').Groups[1].Value.Trim()
    $title = [regex]::Match($text, '(?m)^\s*title:\s*[''"]?([^''"\r\n]+)[''"]?\s*$').Groups[1].Value.Trim()
    $pathCount = ([regex]::Matches($text, '(?m)^  /')).Count

    if ([string]::IsNullOrWhiteSpace($openApiVersion)) {
        throw "Unable to read OpenAPI version from $ProjectionPath."
    }

    if ([string]::IsNullOrWhiteSpace($apiContractVersion)) {
        throw "Unable to read API contract version from $ProjectionPath."
    }

    return [ordered]@{
        openApiVersion = $openApiVersion
        apiContractVersion = $apiContractVersion
        title = $title
        pathCount = $pathCount
    }
}

function Get-GeneratedFiles {
    param(
        [string] $RepoRoot,
        [object] $Metadata,
        [string] $ProjectionRelativePath,
        [string] $ProjectionSha256
    )

    $banner = "Generated by $HarnessName $HarnessVersion from $ProjectionRelativePath ($ProjectionSha256). Do not edit by hand."

    return @(
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/generated/generator-report.json'
            text = $null
            kind = 'generator-report'
        },
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/typescript/grace/src/internal/generated/grace-raw-client-metadata.ts'
            text = @"
// $banner

export const rawClientMetadata = {
  apiContractVersion: "$($Metadata.apiContractVersion)",
  openApiVersion: "$($Metadata.openApiVersion)",
  openApiProjection: "$ProjectionRelativePath",
  openApiProjectionSha256: "$ProjectionSha256",
  generator: "$HarnessName",
  generatorVersion: "$HarnessVersion",
} as const;
"@
            kind = 'typescript-generated-metadata'
        },
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/python/grace-sdk/src/grace_sdk/_generated/grace_raw_client_metadata.py'
            text = @"
# $banner

API_CONTRACT_VERSION = "$($Metadata.apiContractVersion)"
OPENAPI_VERSION = "$($Metadata.openApiVersion)"
OPENAPI_PROJECTION = "$ProjectionRelativePath"
OPENAPI_PROJECTION_SHA256 = "$ProjectionSha256"
GENERATOR = "$HarnessName"
GENERATOR_VERSION = "$HarnessVersion"
"@
            kind = 'python-generated-metadata'
        },
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/python/grace-sdk/src/grace_sdk/_generated/__init__.py'
            text = @"
# $banner
"@
            kind = 'python-generated-package'
        },
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/rust/grace-sdk/src/generated.rs'
            text = @"
// $banner

pub(crate) const API_CONTRACT_VERSION: &str = "$($Metadata.apiContractVersion)";
pub(crate) const OPENAPI_VERSION: &str = "$($Metadata.openApiVersion)";
pub(crate) const OPENAPI_PROJECTION: &str = "$ProjectionRelativePath";
pub(crate) const OPENAPI_PROJECTION_SHA256: &str = "$ProjectionSha256";
pub(crate) const GENERATOR: &str = "$HarnessName";
pub(crate) const GENERATOR_VERSION: &str = "$HarnessVersion";
"@
            kind = 'rust-generated-metadata'
        },
        [pscustomobject]@{
            path = Join-Path $RepoRoot 'sdk/dotnet/Grace.Sdk.Harness/Internal/Generated/GraceRawClientMetadata.cs'
            text = @"
// $banner

namespace Grace.Sdk.Harness.Internal.Generated;

internal static class GraceRawClientMetadata
{
    public const string ApiContractVersion = "$($Metadata.apiContractVersion)";
    public const string OpenApiVersion = "$($Metadata.openApiVersion)";
    public const string OpenApiProjection = "$ProjectionRelativePath";
    public const string OpenApiProjectionSha256 = "$ProjectionSha256";
    public const string Generator = "$HarnessName";
    public const string GeneratorVersion = "$HarnessVersion";
}
"@
            kind = 'dotnet-generated-metadata'
        }
    )
}

$repoRoot = Get-RepoRoot
$projectionRelativePath = 'src/OpenAPI/Grace.OpenAPI.3.1.2.yaml'
$projectionPath = Join-Path $repoRoot $projectionRelativePath

if (-not (Test-Path -LiteralPath $projectionPath -PathType Leaf)) {
    throw "OpenAPI projection not found at $projectionPath."
}

$projectionSha256 = Get-FileSha256 $projectionPath
$metadata = Get-OpenApiMetadata $projectionPath
$generatedFiles = @(Get-GeneratedFiles $repoRoot $metadata $projectionRelativePath $projectionSha256)
$toolVersions = @(
    Get-CommandVersion 'pwsh' @('--version')
    Get-CommandVersion 'dotnet' @('--version')
    Get-CommandVersion 'node' @('--version')
    Get-CommandVersion 'npm' @('--version')
    Get-CommandVersion 'python' @('--version')
    Get-CommandVersion 'cargo' @('--version')
    Get-CommandVersion 'rustc' @('--version')
)

$reportPath = Join-Path $repoRoot 'sdk/generated/generator-report.json'
$report = [ordered]@{
    schemaVersion = $HarnessSchemaVersion
    generatedBy = $HarnessName
    generatorVersion = $HarnessVersion
    generatorPinned = $true
    generatedClientBoundary = 'internal-behind-facades'
    sourceProjection = $projectionRelativePath
    sourceProjectionSha256 = $projectionSha256
    openApiVersion = $metadata.openApiVersion
    apiContractVersion = $metadata.apiContractVersion
    pathCount = $metadata.pathCount
    toolVersionDiagnostics = 'console-only'
    toolVersionCommands = @($toolVersions | ForEach-Object { $_.command })
    generatedFiles = @($generatedFiles |
        Where-Object { $_.kind -ne 'generator-report' } |
        ForEach-Object {
            [ordered]@{
                path = [IO.Path]::GetRelativePath($repoRoot, $_.path).Replace('\', '/')
                kind = $_.kind
            }
        })
}

$reportJson = $report | ConvertTo-Json -Depth 10
$generatedFiles[0].text = "$reportJson`n"
Write-ToolVersionDiagnostics $toolVersions

if ($Mode -eq 'Generate') {
    foreach ($file in $generatedFiles) {
        Write-Utf8NoBomLfFile $file.path $file.text
        Write-Host "Generated $([IO.Path]::GetRelativePath($repoRoot, $file.path))."
    }
}
else {
    $mismatches = New-Object System.Collections.Generic.List[string]

    foreach ($file in $generatedFiles) {
        if (-not (Test-Path -LiteralPath $file.path -PathType Leaf)) {
            $mismatches.Add("Missing $([IO.Path]::GetRelativePath($repoRoot, $file.path)).")
            continue
        }

        $actual = Get-Content -LiteralPath $file.path -Raw
        $expected = $file.text -replace "`r`n", "`n"
        $actualNormalized = $actual -replace "`r`n", "`n"

        if ($actualNormalized -ne $expected) {
            $mismatches.Add("Stale $([IO.Path]::GetRelativePath($repoRoot, $file.path)).")
        }
    }

    if ($mismatches.Count -gt 0) {
        $mismatches | ForEach-Object { Write-Error $_ }
        throw "SDK generated client harness freshness check failed. Run 'pwsh ./sdk/scripts/generate-sdk-clients.ps1 -Mode Generate'."
    }

    Write-Host 'SDK generated client harness freshness check passed.'
}
