// Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (79981a8c946bcc283a58478cbd609c3a49f500488610a6b78e907fb7d247f9d6). Do not edit by hand.

pub(crate) const API_CONTRACT_VERSION: &str = "2023-10-01";
pub(crate) const OPENAPI_VERSION: &str = "3.1.2";
pub(crate) const OPENAPI_PROJECTION: &str = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml";
pub(crate) const OPENAPI_PROJECTION_SHA256: &str = "79981a8c946bcc283a58478cbd609c3a49f500488610a6b78e907fb7d247f9d6";
pub(crate) const GENERATOR: &str = "grace-sdk-harness";
pub(crate) const GENERATOR_VERSION: &str = "0.1.0";