// Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (82bdc533ed082a66e460c1e43c8b4af1bc13d67bf53f4c04fd32ada3dc86a5c0). Do not edit by hand.

pub(crate) const API_CONTRACT_VERSION: &str = "2023-10-01";
pub(crate) const OPENAPI_VERSION: &str = "3.1.2";
pub(crate) const OPENAPI_PROJECTION: &str = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml";
pub(crate) const OPENAPI_PROJECTION_SHA256: &str = "82bdc533ed082a66e460c1e43c8b4af1bc13d67bf53f4c04fd32ada3dc86a5c0";
pub(crate) const GENERATOR: &str = "grace-sdk-harness";
pub(crate) const GENERATOR_VERSION: &str = "0.1.0";