// Generated by grace-sdk-harness 0.1.0 from src/OpenAPI/Grace.OpenAPI.3.1.2.yaml (369a5dcd935a91a02777c06a59aa91e61edcf012198491c6bda124d989bb044b). Do not edit by hand.

pub(crate) const API_CONTRACT_VERSION: &str = "2023-10-01";
pub(crate) const OPENAPI_VERSION: &str = "3.1.2";
pub(crate) const OPENAPI_PROJECTION: &str = "src/OpenAPI/Grace.OpenAPI.3.1.2.yaml";
pub(crate) const OPENAPI_PROJECTION_SHA256: &str = "369a5dcd935a91a02777c06a59aa91e61edcf012198491c6bda124d989bb044b";
pub(crate) const GENERATOR: &str = "grace-sdk-harness";
pub(crate) const GENERATOR_VERSION: &str = "0.1.0";